MACRO command
	const \1_command
	DEF \1 EQUS "db \1_command"
ENDM

; BattleCommandPointers indexes (see data/battle/effect_command_pointers.asm)
	const_def 0
	command checkturn               ; 01
	command checkobedience          ; 02
	command usedmovetext            ; 03
	command doturn                  ; 04
	command critical                ; 05
	command damagestats             ; 06
	command stab                    ; 07
	command damagevariation         ; 08
	command checkhit                ; 09
	command lowersub                ; 0a
	command moveanimnosub           ; 0b
	command raisesub                ; 0c
	command failuretext             ; 0d
	command applydamage             ; 0e
	command criticaltext            ; 0f
	command supereffectivetext      ; 10
	command checkfaint              ; 11
	command poisontarget            ; 12
	command sleeptarget             ; 13
	command draintarget             ; 14
	command eatdream                ; 15
	command burntarget              ; 16
	command freezetarget            ; 17
	command paralyzetarget          ; 18
	command selfdestruct            ; 19
	command mirrormove              ; 1a
	command statup                  ; 1b
	command statdown                ; 1c
	command resetstats              ; 1d
	command forceswitch             ; 1e
	command endloop                 ; 1f
	command flinchtarget            ; 20
	command ohko                    ; 21
	command mist                    ; 22
	command focusenergy             ; 23
	command confuse                 ; 24
	command confusetarget           ; 25
	command heal                    ; 26
	command transform               ; 27
	command poison                  ; 28
	command paralyze                ; 29
	command substitute              ; 2a
	command rechargenextturn        ; 2b
	command mimic                   ; 2c
	command metronome               ; 2d
	command splash                  ; 2e
	command cleartext               ; 2f
	command charge                  ; 30
	command checkcharge             ; 31
	command effect0x3c              ; 32
	command rampage                 ; 33
	command checkrampage            ; 34
	command constantdamage          ; 35
	command counter                 ; 36
	command encore                  ; 37
	command painsplit               ; 38
	command snore                   ; 39
	command lockon                  ; 3a
	command sketch                  ; 3b
	command defrostopponent         ; 3c
	command sleeptalk               ; 3d
	command destinybond             ; 3e
	command falseswipe              ; 3f
	command healbell                ; 40
	command kingsrock               ; 41
	command arenatrap               ; 42
	command nightmare               ; 43
	command defrost                 ; 44
	command curse                   ; 45
	command foresight               ; 46
	command startsandstorm          ; 47
	command checkrollout            ; 48
	command rolloutpower            ; 49
	command effect0x5d              ; 4a
	command furycutter              ; 4b
	command attract                 ; 4c
	command present                 ; 4d
	command damagecalc              ; 4e
	command safeguard               ; 4f
	command checksafeguard          ; 50
	command getmagnitude            ; 51
	command batonpass               ; 52
	command healmorn                ; 53
	command healday                 ; 54
	command healnite                ; 55
	command hiddenpower             ; 56
	command startrain               ; 57
	command startsun                ; 58
	command attackup                ; 59
	command defenseup               ; 5a
	command speedup                 ; 5b
	command specialattackup         ; 5c
	command specialdefenseup        ; 5d
	command accuracyup              ; 5e
	command evasionup               ; 5f
	command attackup2               ; 60
	command defenseup2              ; 61
	command speedup2                ; 62
	command specialattackup2        ; 63
	command specialdefenseup2       ; 64
	command accuracyup2             ; 65
	command evasionup2              ; 66
	command attackdown              ; 67
	command defensedown             ; 68
	command speeddown               ; 69
	command specialattackdown       ; 6a
	command specialdefensedown      ; 6b
	command accuracydown            ; 6c
	command evasiondown             ; 6d
	command attackdown2             ; 6e
	command defensedown2            ; 6f
	command speeddown2              ; 70
	command specialattackdown2      ; 71
	command specialdefensedown2     ; 72
	command accuracydown2           ; 73
	command evasiondown2            ; 74
	command statupmessage           ; 75
	command statdownmessage         ; 76
	command statupfailtext          ; 77
	command statdownfailtext        ; 78
	command effectchance            ; 79
	command statdownanim            ; 7a
	command statupanim              ; 7b
	command switchturn              ; 7c
	command fakeout                 ; 7d
	command bellydrum               ; 7e
	command psychup                 ; 7f
	command checkfuturesight        ; 80
	command futuresight             ; 81
	command teleport                ; 82
	command resettypematchup        ; 83
	command allstatsup              ; 84
	command bidefailtext            ; 85
	command raisesubnoanim          ; 86
	command lowersubnoanim          ; 87
	command clearmissdamage         ; 88
	command movedelay               ; 89
	command moveanim                ; 8a
	command tristatuschance         ; 8b
	command supereffectivelooptext  ; 8c
	command startloop               ; 8d
	command starthail               ; 8e
DEF EFFECT_COMMANDS_1 EQU const_value - 1
	command doubleminimizedamage    ; 8f
	command doubleflyingdamage      ; 90
	command doubleundergrounddamage ; 91
	command skipsuncharge           ; 92
	command thunderaccuracy         ; 93
	command mirrorcoat              ; 94
	command clearhazards            ; 95
	command perishsong              ; 96
	command spikes                  ; 97
	command endure                  ; 98
	command protect                 ; 99
	command thief                   ; 9a
	command screen                  ; 9b
	command leechseed               ; 9c
	command disable                 ; 9d
	command recoil                  ; 9e
	command traptarget              ; 9f
	command curl                    ; a0
	command storeenergy             ; a1
	command unleashenergy           ; a2
	command spite                   ; a3
	command conversion              ; a4
	command conversion2             ; a5
	command beatupfailtext          ; a6
	command beatup                  ; a7
	command kickcounter             ; a8
	command triplekick              ; a9
	command ragedamage              ; aa
	command buildopponentrage       ; ab
	command rage                    ; ac
	command payday                  ; ad
	command pursuit                 ; ae
	command happinesspower          ; af
	command frustrationpower        ; b0
	command lowkick                 ; b1
DEF EFFECT_COMMANDS_2 EQU const_value - 1

	const_def -1, -1
	command endmove                 ; ff
	command endturn                 ; fe
